services:
  postgres:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-test:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-devmigrations:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres-devmigrations
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: devmigruser
      POSTGRES_PASSWORD: devmigrpass
      POSTGRES_DB: devmigrdb
    volumes:
      - pgdata-devmigr:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
  pgdata-test:
  pgdata-devmigr:
