services:
  postgres-test:
    image: postgis/postgis:17-3.5
    container_name: postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata-test:
