spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      root: ERROR
springdoc:
  swagger-ui:
    path: /api/v1/swagger
    enabled: true
  api-docs:
    path: /api/v1/docs
    enabled: true
