spring:
  application:
    name: DondeSiempre
  profiles:
    active: ${SPRING_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquidbase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
