spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  logging:
    level:
      root: ERROR
springdoc:
  swagger-ui:
    path: /api/v1/swagger
    enabled: true
  api-docs:
    path: /api/v1/docs
    enabled: true
