spring:
  config:
    activate:
      on-profile: dev-migration
  datasource:
    url: jdbc:postgresql://localhost:5434/devmigrdb
    username: devmigruser
    password: devmigrpass
  logging:
    level:
      root: ERROR
springdoc:
  swagger-ui:
    path: /api/v1/swagger
    enabled: true
  api-docs:
    path: /api/v1/docs
    enabled: true
