spring:
  config:
    activate:
      on-profile: dev-migration
  datasource:
    url: jdbc:postgresql://localhost:5434/devmigrdb
    username: devmigruser
    password: devmigrpass
  logging:
    level:
      root: ERROR
